# Generated by Django 4.0.3 on 2022-03-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rehber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=360, null=True)),
                ('soyisim', models.CharField(max_length=360, null=True)),
                ('numara', models.CharField(max_length=360, null=True)),
                ('email', models.CharField(max_length=360, null=True)),
                ('gsm', models.CharField(max_length=360, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=360, null=True)),
                ('description', models.CharField(max_length=360, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('published', models.DateField(blank=True, default=None, null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
